@startuml
    title Model

    hide class circle
    hide class fields
    hide class methods
    hide enum circle
    hide enum fields
    hide enum methods

    class ComputationTask
    class ComputationApplication
    class ComputationInput
    class ComputationStep
    class ComputationStepPackage
    class ComputationStepParam
    class ComputationRunnable
    class ComputationTopic
    class Computation
    enum ComputationStatus
    class ComputationDetails
    class MachineComputingStatus
    class Machine
    class MachineMetrics
    class MachineMetricValue

    ComputationDetails <|-- ComputationTask
    ComputationDetails <|-- ComputationStatus
    ComputationTask *-- ComputationApplication
    ComputationTask o-- ComputationInput
    ComputationApplication o-- "0..*" ComputationStepParam
    ComputationInput ..> ComputationApplication
    ComputationStepPackage *-- "1..*" ComputationStep
    ComputationStepPackage ..> ComputationApplication
    ComputationStepPackage "1" -do-* ComputationTask
    ComputationStep o-- "0..*" ComputationStepParam
    ComputationRunnable *-- "1" ComputationStep
    ComputationRunnable o-- ComputationTopic
    Computation *-- "1"ComputationStepPackage
    Computation *-- "1" ComputationInput
    Machine o-- MachineMetrics
    MachineMetrics o-- MachineMetricValue
    MachineComputingStatus o-- MachineMetrics
    MachineComputingStatus o-- "0..*" ComputationStatus
@enduml