@startuml
    title Model

    hide class circle
    hide class fields
    hide class methods

    class ComputationTask
    class ComputationApplication
    class ComputationInput
    class ComputationStep
    class ComputationStepPackage
    class ComputationStepParam
    class ComputationRunnable
    class ComputationTopic
    class Computation
    class ComputationStatus
    class ComputationDetails
    class Machine
    class MachineMetrics
    class MachineMetricValue

    ComputationDetails <|-- ComputationTask
    ComputationDetails <|-- ComputationStatus
    ComputationTask *-- ComputationApplication
    ComputationTask o-- ComputationInput
    ComputationApplication o-- "0..*" ComputationStepParam
    ComputationInput ..> ComputationApplication
    ComputationStepPackage *-- "1..*" ComputationStep
    ComputationStepPackage "1" --* ComputationApplication
    ComputationStep o-- "0..*" ComputationStepParam
    ComputationRunnable *-- "1" ComputationStep
    ComputationRunnable o-- ComputationTopic
    Computation *-- "1"ComputationStepPackage
    Computation *-- "1" ComputationInput
    Machine o-- MachineMetrics
    MachineMetrics o-- MachineMetricValue
@enduml